#!/bin/bash
declare GIT_ROOT=`git rev-parse --show-superproject-working-tree --show-toplevel | head -1`
declare HOOK_NAME=`basename $0`
declare LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"
# Prefer project's hook than global hooks
if [ -e $LOCAL_HOOK ]; then
    $LOCAL_HOOK
fi
