#!/bin/bash
declare GIT_ROOT=$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)
declare HOOK_NAME=$(basename "$0")
declare LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"
declare LOCAL_HOOK_ALT="${GIT_ROOT}/.githooks/${HOOK_NAME}"
declare scriptDir=$(cd $(dirname $0);pwd)
declare IGNORE_GLOBAL_HOOKS="$(dirname "${scriptDir}")/IGNORE_GLOBAL_HOOKS"

# Prefer project's hook than global hooks
if [ -e "$LOCAL_HOOK" ]; then
    $LOCAL_HOOK
    # if local hook exit with non-zero, exit with non-zero
    if [ $? -ne 0 ]; then
        exit 1
    fi
    export LOCAL_HOOK_IS_CALLED=1
fi
if [ -e "$LOCAL_HOOK_ALT" ]; then
    $LOCAL_HOOK_ALT
    # if local hook exit with non-zero, exit with non-zero
    if [ $? -ne 0 ]; then
        exit 1
    fi
    export LOCAL_HOOK_IS_CALLED=1
fi

if cat "${IGNORE_GLOBAL_HOOKS}" | grep -q "${GIT_ROOT}"; then
    exit 0
fi
# NO_VERIFY_GLOBAL_HOOKS=1 git commit -m "commit_message"
if [ -n "${NO_VERIFY_GLOBAL_HOOKS}" ]; then
  exit 0
fi
