#!/bin/bash

source $(dirname ${0})/_local-hook-exec

# GIL: Git CommitをNotionに記録する仕組み
declare GIT_COMMIT_LOG
declare GIT_COMMIT_MSG
declare GIT_COMMIT_HASH
declare GIT_REPO_HTTP_URL
GIT_COMMIT_LOG=$(git log -n 1 HEAD --format="format:%h %s")
GIT_COMMIT_HASH=$(echo "${GIT_COMMIT_LOG}" | cut -d' ' -f1)
GIT_COMMIT_MSG=$(echo "${GIT_COMMIT_LOG}" | cut -d' ' -f2-)

currentDirName=$(basename $(pwd))
parentDirName=$(basename $(dirname $(pwd)))
GIT_REPO_HTTP_URL=$( (git config --get remote.origin.url || echo "https://github.com/${parentDirName}/${currentDirName}") | sed -e 's/.git$//'  -e 's/^ssh:\/\/git@/https:\/\//' -e 's/^git@github.com:/https:\/\/github.com\//' )

# call as subprocess
bash "$(dirname ${0})/post-notion-gil.sh" "${GIT_COMMIT_HASH}" "${GIT_COMMIT_MSG}" "${GIT_REPO_HTTP_URL}" > /dev/null & exit 0;
