#!/bin/bash

source $(dirname ${0})/_local-hook-exec

# GIL: Git CommitをNotionに記録する仕組み
declare GIT_COMMIT_LOG
declare GIT_COMMIT_MSG
declare GIT_COMMIT_HASH
declare GIT_REPO_HTTP_URL
declare NOTION_API_TOKEN
declare NOTION_DATABASE_ID
GIT_COMMIT_LOG=$(git log -n 1 HEAD --format="format:%h %s")
GIT_COMMIT_HASH=$(echo "${GIT_COMMIT_LOG}" | cut -d' ' -f1)
GIT_COMMIT_MSG=$(echo "${GIT_COMMIT_LOG}" | cut -d' ' -f2-)
GIT_REPO_HTTP_URL=$(git config --get remote.origin.url | sed -e 's/.git$//' -e 's/^git@/https:\/\//')
# Require 1Password: "GIL_NOTION"
declare scriptDir
declare DOT_ENV
scriptDir=$(cd $(dirname ${BASH_SOURCE:-$0}) || exit; pwd)
DOT_ENV="${scriptDir}/../.env"
export $(grep -v '^#' "${DOT_ENV}" | xargs)


NOTION_PAYLOAD=$(cat <<EOF
{
  "parent": { "database_id": "${GIL_NOTION_DATABASE_ID}" },
  "properties": {
    "Message": {
      "title": [
        {
          "text": {
            "content": "${GIT_COMMIT_MSG}"
          }
        }
      ]
    },
    "Hash": {
      "rich_text": [{
        "text": {
          "content": "${GIT_COMMIT_HASH}"
        }
      }]
    },
    "Repo": {
      "url": "${GIT_REPO_HTTP_URL}"
    }
  }
}
EOF
)
curl -s -X POST https://api.notion.com/v1/pages \
  -H "Authorization: Bearer ${GIL_NOTION_API_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "Notion-Version: 2022-02-22" \
  --data "${NOTION_PAYLOAD}" > /dev/null
